### ISSUE TITLE
Null MX validation

### ISSUE THREAD

**Issue by jace** [michaelherold/pyIsEmail#10]
[RFC 7505](https://tools.ietf.org/html/rfc7505) specifies "null MX" for when a domain explicitly does not support email. This is testable with the `example.*` domains:

```
example.org mail is handled by 0 .
```

However, pyIsEmail when using `check_dns=True` does not test for RFC 7505 and accepts null MX records as valid.

```python
>>> is_email('example@example.org', check_dns=True, diagnose=True)
<ValidDiagnosis: VALID>
```

**Comment by michaelherold** [comment]
This looks reasonable. I'd be happy to accept a PR.

**Comment by IPENprj** [comment]
Hi there,
Is this why Domains with MX that has no A Record, validated?

**Comment by bmcculley** [comment]
Opened PR #22 which checks the returned MX record(s) preference.
