### ISSUE TITLE
release v1.3.3 ?

### ISSUE THREAD

**Issue by d3vm0nk3y** [michaelherold/pyIsEmail#16]
any chance to create a new release with the gtld-validator update?
what can I do to help?

**Comment by michaelherold** [comment]
I'll do my best to get this out tomorrow. It'll be v1.4.0 since there is added functionality.

**Comment by d3vm0nk3y** [comment]
that is awesome, thanks !!!
please let me know if there is anything I could help.

**Comment by michaelherold** [comment]
Done!
