### ISSUE TITLE
DeprecationWarning in python 3.8

### ISSUE THREAD

**Issue by abtechbit** [michaelherold/pyIsEmail#21]
Any plans releasing new version that includes https://github.com/michaelherold/pyIsEmail/pull/19 to be available in PiPY to avoid deprecation warning?

Appreciate your work on this great library!

**Comment by michaelherold** [comment]
This should now be solved by v2.0.0, which you can see [on PyPI](https://pypi.org/manage/project/pyIsEmail/release/2.0.0/), [in the main branch](https://github.com/michaelherold/pyIsEmail/commit/000346516c2971aae7ec073c6ebe8bf56a5c1af4), and [as a tag](https://github.com/michaelherold/pyIsEmail/releases/tag/v2.0.0).

Cheers!
