### ISSUE TITLE
PyPandoc requirement breaks installation

### ISSUE THREAD

**Issue by jace** [michaelherold/pyIsEmail#4]
Installing pyIsEmail requires PyPandoc, which fails if there's no Pandoc on the computer. Since this is most likely the case, and since Pandoc isn't required for using PyIsEmail, this is an issue. Pandoc should be optional.

**Comment by michaelherold** [comment]
`pypandoc` is in the `setup_require` array, which I didn't think was necessary when installing via `pip`. Is that not the case?

Really it's only needed for releasing new versions of the gem -- and only because the Cheeseshop doesn't support Markdown as a readme format.
