### ISSUE TITLE
pypi page looks strange

### ISSUE THREAD

**Issue by guettli** [michaelherold/pyIsEmail#5]
Hi,

your page on pypi:

https://pypi.python.org/pypi/pyIsEmail/

looks strange. I guess the wiki-format you use is not supported by pypi.

**Comment by michaelherold** [comment]
Correct. It's written in Markdown, while the current Cheeseshop only supports ReStructured Text. Is that something off-putting to you as a potential user?

**Comment by guettli** [comment]
I searched the web and found an online converter: http://johnmacfarlane.net/pandoc/try/

I tried it with README.md and the result looked good. I guess the filename need to be change after the conversion. What should the new filename be?

**Comment by michaelherold** [comment]
Thanks for looking. I will just do the conversion by hand, since there was a report in #4 that relying on Pandoc for the conversion was causing an installation error.
