### ISSUE TITLE
The wheel fixes the version of dnspython to dnspython3

### ISSUE THREAD

**Issue by maparent** [michaelherold/pyIsEmail#6]
A pip install pyIsEmail in python 2.7 gets the py2.py3 wheel from pypi, whose metadata contains a fixed requirement for dnspython3. You should upload a py2 and py3 wheel separately to pypi.
Regards.

**Comment by michaelherold** [comment]
Thanks! I hadn't realized that the wheel wouldn't take into account the toggled dnspython version. I will release a py2 and py3 version soon.

**Comment by karthikb351** [comment]
:bump:

Any update on this?

**Comment by jace** [comment]
This problem continues to affect anyone using a project that depends on pyisemail. I get bug reports on my projects every week. :(

**Comment by michaelherold** [comment]
Hmm, I thought I had released a new version. I'll get it out today.

Sorry about the wait.

**Comment by michaelherold** [comment]
I've released v1.3.1 that should take care of the issue. Please let me know if there are any other problems.
